// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk4_CQzwNjJAp9xBCOoZIxtQIn-9PbbFk',
    appId: '1:1024216708131:web:53ecbc4f307a80d7b32d96',
    messagingSenderId: '1024216708131',
    projectId: 'mi-vecino3',
    authDomain: 'mi-vecino3.firebaseapp.com',
    storageBucket: 'mi-vecino3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFzdRLVeCGqHc5rDyB-zqBzNSci75wVz4',
    appId: '1:1024216708131:android:e5ecf6dcac3f0ec5b32d96',
    messagingSenderId: '1024216708131',
    projectId: 'mi-vecino3',
    storageBucket: 'mi-vecino3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLJUuJmOY1yO_GGf7FVz2R-6B5RSq1-1o',
    appId: '1:1024216708131:ios:7e1166e051f56301b32d96',
    messagingSenderId: '1024216708131',
    projectId: 'mi-vecino3',
    storageBucket: 'mi-vecino3.firebasestorage.app',
    iosBundleId: 'com.example.miVecino',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLJUuJmOY1yO_GGf7FVz2R-6B5RSq1-1o',
    appId: '1:1024216708131:ios:7e1166e051f56301b32d96',
    messagingSenderId: '1024216708131',
    projectId: 'mi-vecino3',
    storageBucket: 'mi-vecino3.firebasestorage.app',
    iosBundleId: 'com.example.miVecino',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk4_CQzwNjJAp9xBCOoZIxtQIn-9PbbFk',
    appId: '1:1024216708131:web:e3afb12acb736b65b32d96',
    messagingSenderId: '1024216708131',
    projectId: 'mi-vecino3',
    authDomain: 'mi-vecino3.firebaseapp.com',
    storageBucket: 'mi-vecino3.firebasestorage.app',
  );
}
